#pragma once

enum statusCode {
	NOT_A_STATUS_CODE = 0,
	CONTINUE = 100,
	OK = 200,
	CREATED = 201,
	NO_CONTENT = 204,
	MOVED_PERMANENTLY = 301,
	FOUND = 302,
	BAD_REQUEST = 400,
	FORBIDDEN = 403,
	NOT_FOUND = 404,
	METHOD_NOT_ALLOWED = 405,
	TIMEOUT = 408,
	LENGTH_REQUIRED = 411,
	ENTITY_TOO_LARGE = 413,
	URI_TOO_LONG = 414,
	EXPECTATION_FAILED = 417,
	REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
	INTERNAL_SERVER_ERROR = 500,
	NOT_IMPLEMENTED = 501,
	HTTP_VERSION_NOT_SUPPORTED = 505
};

enum convState {
	READ_CLIENT,
	WRITE_CLIENT,
	EOF_CLIENT,
	FINISH,
	READ_EXEC,
	WRITE_EXEC,
	PARSE,
	PARSE_BODY,
	VALIDATE,
	RESPONSE,
	EXEC,
	TO_READ,
	TO_SEND,
	IS_SENT,
	CLIENT_TIMEOUT
};
