#pragma once

enum statusCode {
	NOT_A_STATUS_CODE = 0,
	BAD_REQUEST = 400,
	CONTENT_TOO_LARGE = 413,
	URI_TOO_LONG = 414,
	REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
	NOT_IMPLEMENTED = 501,
	HTTP_VERSION_NOT_SUPPORTED = 505
};

enum convState {
	READ_CLIENT,
	WRITE_CLIENT,
	EOF_CLIENT,
	FINISH,
	READ_EXEC,
	WRITE_EXEC,
	PARSE_HEADER,
	PARSE_BODY,
	DRAIN_BUFFER,
	VALIDATE,
	RESPONSE,
	EXEC,
	IS_SENT
};
